## Google BigData Showcase
BigQuery ML Tutorial 02 - 농구 점수 예측하기  
Edited by 김하제

### BigQuery 라이브러리 호출

In [1]:
from google.cloud import bigquery
client = bigquery.Client()

### 데이터셋 설정 "bqml_tutorial"

In [2]:
dataset = bigquery.Dataset(client.dataset('bqml_tutorial'))
#dataset.location = 'US'
#client.create_dataset(dataset)

### Jupyter에서 BigQuery SQL을 사용하기 위한 magic 명령어 클라이언트 라이브러리 호출

In [3]:
%load_ext google.cloud.bigquery

### 1. Google Analytics Sessions 샘플 데이터 호출하기

In [4]:
%%bigquery
SELECT
  *
FROM
  bqml_tutorial.wide_games
WHERE
  game_id != 'f1063e80-23c7-486b-9a5e-faa52beb2d83'
LIMIT 15

,game_id,season,scheduled_date,team_id,opponent_id,total_three_points_made,total_three_points_att,team_points_avg_last_1,team_points_avg_last_5,team_points_avg_last_10,...,opponent_opp_team_tech_fouls_std_last_5,opponent_opp_team_tech_fouls_std_last_10,opponent_opp_coach_tech_fouls_std_last_5,opponent_opp_coach_tech_fouls_std_last_10,opponent_opp_foulouts_std_last_5,opponent_opp_foulouts_std_last_10,opponent_opp_score_delta_std_last_5,opponent_opp_score_delta_std_last_10,opponent_opp_possessions_std_last_5,opponent_opp_possessions_std_last_10
0,54396c2c-5a5b-4892-afc8-fa69b49dd97b,2013,2014-03-18,2013:8736b67f-5924-400b-bf94-3bd804c36600,2013:f770d3a2-221c-49ce-9c7a-680f7417fe9e,13,40,56.0,67.4,68.9,...,0.0,0.0,0.0,0.0,NaN,NaN,15.14,15.53,3.83,7.51
1,1a468fb6-8545-4e8d-87d8-ef0f7d494365,2013,2014-03-19,2013:0d8a328f-20ce-410b-bed1-15fc01308aaf,2013:52df1e19-b142-4a76-a439-ad68455d0581,6,28,78.0,70.6,68.9,...,0.0,0.0,0.0,0.0,NaN,NaN,6.55,9.30,3.75,4.89
2,c8ff45e3-3ef2-4241-9c5c-65cca4a4b60c,2013,2014-03-20,2013:9fccbf28-2858-4263-821c-fdefb3c7efa3,2013:24051034-96bb-4f78-a3a6-312f3258780f,8,30,43.0,57.0,62.8,...,0.0,0.0,0.0,0.0,NaN,NaN,12.50,9.87,7.83,7.10
3,51d7ce42-bfc7-41cc-b995-48fdb8fbbc35,2013,2014-03-20,2013:b827dbdf-230f-4916-9703-3bb9004e26eb,2013:c10544de-e3bd-4776-ba2e-83df8c017fd1,9,37,49.0,67.6,67.3,...,0.0,0.0,0.0,0.0,0.0,0.0,5.78,8.98,9.01,6.78
4,37902a80-a982-4df7-b5a4-89b54ca662b2,2013,2014-03-20,2013:1e42cce3-236b-4f3e-9650-2c45e6332e1e,2013:52df1e19-b142-4a76-a439-ad68455d0581,13,27,68.0,63.8,66.8,...,0.0,0.0,0.0,0.0,NaN,NaN,7.88,10.40,4.41,4.99
5,ae2be8bc-de3b-49d8-b22a-464d92455f54,2013,2014-03-21,2013:1b1977ec-b32f-4ce3-95a4-d07bab4816cd,2013:683ab61f-546f-44da-b085-c3a5740554aa,12,36,70.0,71.0,69.0,...,0.0,0.0,0.0,0.0,NaN,NaN,15.44,14.66,3.37,5.93
6,17c101d9-1da9-4c65-8599-9cf758429088,2013,2014-03-21,2013:db6e1cab-3fa3-4a93-a673-8b2a358ff4bf,2013:f8b1bf00-5b73-4ac4-98c0-ec554027ae32,6,34,65.0,76.2,74.1,...,0.0,0.0,0.0,0.3,NaN,NaN,8.28,8.08,4.72,4.67
7,668626a5-76c4-4194-a1f4-65e85a157e33,2013,2014-03-21,2013:2f4d21f8-6d5f-48a5-abca-52a30583871a,2013:8ab00d43-840a-4c96-bdee-bf88fa6e3f11,12,33,66.0,65.8,69.3,...,0.0,0.0,0.0,0.3,NaN,NaN,10.14,13.62,6.55,5.75
8,4a3f1890-ce8d-48cc-ba9c-107fc3e58fc4,2013,2014-03-21,2013:e9ca48b2-00ba-41c0-a02b-6885a2da1ff1,2013:7d3b9c72-cbdd-4b64-9aa3-a5bde9b75fdc,8,31,75.0,72.8,77.2,...,0.0,0.0,0.0,0.0,NaN,NaN,8.16,10.13,9.14,7.62
9,6676d427-0ba6-4215-bf8e-381e08748614,2013,2014-03-21,2013:88104678-e53b-43b3-82f7-efb3a11cedb9,2013:b827dbdf-230f-4916-9703-3bb9004e26eb,5,25,62.0,68.0,72.4,...,0.0,0.0,0.0,0.0,NaN,NaN,12.66,14.50,2.00,3.99
10,9dd937a4-2b43-47d0-991d-a0dbd7ac1cfc,2013,2014-03-21,2013:6ed15092-2670-450a-99c2-61d861e87644,2013:ad4bc983-8d2e-4e6f-a8f9-80840a786c64,13,27,69.0,63.8,69.8,...,0.0,0.0,0.0,0.0,NaN,NaN,13.87,12.44,2.93,6.31
11,32a8c6b0-df2d-4869-9625-e192b91ad82d,2013,2014-03-22,2013:2267a1f4-68f6-418b-aaf6-2aa0c4b291f1,2013:d203f38a-a166-4258-bca2-e161b591ecfb,9,36,60.0,67.0,68.9,...,0.0,0.0,0.4,0.3,NaN,NaN,8.09,10.78,4.62,6.81
12,90c78781-81db-4e71-9542-16febc9955da,2013,2014-03-22,2013:8cd24de1-2be8-4b77-bcfa-47be0495a5f4,2013:632616c5-2dbb-4017-a449-c9dfc303f026,7,26,77.0,66.4,62.2,...,0.0,0.0,0.0,0.0,NaN,NaN,4.00,6.73,2.65,7.38
13,93d21134-086c-496b-a9d1-a5798f4dafe7,2013,2014-03-22,2013:b795ddbc-baab-4499-8803-52e8608520ab,2013:1e42cce3-236b-4f3e-9650-2c45e6332e1e,6,32,71.0,81.8,78.5,...,0.0,0.0,0.0,0.3,NaN,NaN,5.08,5.35,5.78,5.54
14,bad6158f-8954-4cc5-bd5d-9d06c7fffd71,2013,2014-03-22,2013:c7569eae-5b93-4197-b204-6f3a62146b25,2013:1da70895-f77f-44ef-b216-d63c02e696eb,19,46,75.0,75.4,74.9,...,0.0,0.0,0.0,0.0,NaN,NaN,13.11,9.97,3.97,4.53

### 2. 모델 만들기

In [7]:
%%bigquery
CREATE OR REPLACE MODEL bqml_tutorial.ncaa_model OPTIONS(
  model_type='linear_reg', max_iteration=50) AS
SELECT
  * EXCEPT(
    game_id, season, scheduled_date,
    total_three_points_made,
    total_three_points_att),
  total_three_points_att as label
FROM
  bqml_tutorial.wide_games
WHERE
  # remove the game to predict
  game_id != 'f1063e80-23c7-486b-9a5e-faa52beb2d83'

Empty DataFrame
Columns: []
Index: []

### 3. 모델 학습 정보 보기

In [8]:
%%bigquery
SELECT
  *
FROM
  ML.TRAINING_INFO(MODEL `bqml_tutorial.ncaa_model`)

   training_run  iteration        loss   eval_loss  duration_ms  learning_rate
0             0          9   46.676759   97.574771         9169           0.10
1             0          8   54.230652  117.709800        11028           0.05
2             0          7   64.009904  119.191259         9454           0.05
3             0          6   77.645875  143.565330         7795           0.05
4             0          5   96.821618  148.159515         9193           0.05
5             0          4  124.060249  193.830190         9208           0.05
6             0          3  163.280971  207.578136        14012           0.05
7             0          2  221.010915  296.070452         7762           0.05
8             0          1  310.393369  339.965668         7333           0.05
9             0          0  524.281301  587.488959         6357           0.20

### 4. 학습된 모델 평가하기

In [9]:
%%bigquery
WITH eval_table AS (
SELECT
  *,
  total_three_points_att AS label
FROM
  `bqml_tutorial.wide_games` )
SELECT
  *
FROM
  ML.EVALUATE(MODEL `bqml_tutorial.ncaa_model`,
    TABLE eval_table)

,mean_absolute_error,mean_squared_error,mean_squared_log_error,median_absolute_error,r2_score,explained_variance
0,5.713375,57.099564,0.035362,4.512607,0.245905,0.414163

### 5. 평가된 모델로 예측하기

In [10]:
%%bigquery
  WITH game_to_predict AS (
  SELECT
    *
  FROM
    `bqml_tutorial.wide_games`
  WHERE
    game_id='f1063e80-23c7-486b-9a5e-faa52beb2d83' )
SELECT
  truth.game_id AS game_id,
  total_three_points_att,
  predicted_total_three_points_att
FROM (
  SELECT
    game_id,
    predicted_label AS predicted_total_three_points_att
  FROM
    ML.PREDICT(MODEL `bqml_tutorial.ncaa_model`,
      table game_to_predict) ) AS predict
JOIN (
  SELECT
    game_id,
    total_three_points_att AS total_three_points_att
  FROM
    game_to_predict) AS truth
ON
  predict.game_id = truth.game_id

,game_id,total_three_points_att,predicted_total_three_points_att
0,f1063e80-23c7-486b-9a5e-faa52beb2d83,50,48.631394